services:
  etikettserver:
    build: .
    privileged: true
    restart: unless-stopped
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - "5000:5000"
    volumes:
      - "/run/cups/cups.sock:/run/cups/cups.sock"
      - "/var/run/dbus:/var/run/dbus"
    # environment:
      # - FQDN=  # Only allow requests from this domain