services:
  etikettserver:
    build: .
    privileged: true
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - "/run/cups/cups.sock:/run/cups/cups.sock"
    # environment:
      # - FQDN=  # Only allow requests from this domain